"""Added fields to Contact model

Revision ID: 9a27c938f263
Revises: b7ee12b28ca8
Create Date: 2025-02-18 02:34:12.540159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a27c938f263'
down_revision: Union[str, None] = 'b7ee12b28ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('company', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('job_title', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('linkedin_url', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('last_contacted', sa.DateTime(), nullable=True))
    op.add_column('contacts', sa.Column('follow_up_date', sa.DateTime(), nullable=True))
    op.add_column('contacts', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('contacts', sa.Column('relationship_strength', sa.Integer(), nullable=True))
    op.add_column('contacts', sa.Column('met_at', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'contacts', ['linkedin_url'])
    op.drop_column('contacts', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contacts', type_='unique')
    op.drop_column('contacts', 'met_at')
    op.drop_column('contacts', 'relationship_strength')
    op.drop_column('contacts', 'notes')
    op.drop_column('contacts', 'follow_up_date')
    op.drop_column('contacts', 'last_contacted')
    op.drop_column('contacts', 'linkedin_url')
    op.drop_column('contacts', 'job_title')
    op.drop_column('contacts', 'company')
    # ### end Alembic commands ###
